### ISSUE TITLE
AttributeError: 'Seq2SeqModelOutput' object has no attribute 'cross_attentions'

### ISSUE THREAD

**Issue by 453001323** [Liadrinz/transformers-copy-mechanism#1]
你好，我在运行您的程序时出现报错：AttributeError: 'Seq2SeqModelOutput' object has no attribute 'cross_attentions' ,请问这个如何解决？

**Comment by Liadrinz** [comment]
应该是transformers版本的问题，请问你用的transformers是什么版本的，我的是4.24.0
