### ISSUE TITLE
copy_module 的问题

### ISSUE THREAD

**Issue by BNDSllx** [Liadrinz/transformers-copy-mechanism#2]
你好，请问在 `modeling.py` 代码中，`BartForConditionalGenerationWithCopyMech` 类的 `forward` 方法里，我理解`src_input_ids` 是要copy序列处理后的 input_id，然后 `input_ids` 是本身给到encoder的输入，那为啥在训练阶段和推理阶段调用 `copy_module` 方法的时候用的输入 id 不一样呢？
```python
if labels is not None:
    # Training
    cross_attentions = outputs.cross_attentions[-1].mean(dim=1)
    p_gen, cp_logits = self.copy_module.forward(input_ids, cross_attentions, outputs.encoder_last_hidden_state, hidden_states)
    p_copy = 1 - p_gen
    logits = p_gen * lm_logits + p_copy * cp_logits
else:
    # Inference (Step-by-step Decoding)
    cross_attentions = outputs.cross_attentions[-1].mean(dim=1)
    p_gen, cp_logits = self.copy_module.forward(src_input_ids, cross_attentions, encoder_outputs[0], hidden_states)
    p_copy = 1 - p_gen
    logits = p_gen * lm_logits + p_copy * cp_logits
```

**Comment by BNDSllx** [comment]
另外，同类下的 `_expand_inputs_for_generation` 和 `_prepare_encoder_decoder_kwargs_for_generation` 是在哪里调用的呢？在原huggingface库中好像没见到类似函数？谢谢！

**Comment by Liadrinz** [comment]
您好~您的理解没有问题。只不过在调用Bart的`generate`方法进行推理的时候，只有第一次过模型的时候会输入source序列的`input_ids`，后续都是利用`past_key_values`，所以后续输入的input_ids为None，所以引入`src_input_ids`这个变量是为了在推理的时候仍然能访问到source序列的input_ids. 当然也可以有别的实现方式。

另外，`_expand_inputs_for_generation`和`_prepare_encoder_decoder_kwargs_for_generation`是在transformers.generation_utils中（最新版的transformers的话应该是在transformers.generation.utils）被多重继承过去的。

**Comment by BNDSllx** [comment]
谢谢，那我这样理解可以嘛？就是目前您的代码里面的 `src_input_id` 实际上就是 `input_id`，然后训练的时候实际上输入 `src_input_ids` 也是可以的？

**Comment by Liadrinz** [comment]
没错`src_input_ids`就是`input_ids`。但如果训练时调用`BartForConditionalGenerationWithCopyMech.forward`时指定`src_input_ids`而不指定`input_ids`，那以目前的代码实现来说是不行的，因为训练时输入`src_input_ids`不会被`BartForConditionalGenerationWithCopyMech`内的copy_module接收。我之后会看看能不能把`input_ids`和`src_input_ids`合并一下。

**Comment by BNDSllx** [comment]
好的，非常感谢！
